resource_group_name = "my-rg"
location            = "East US"
vnet_name           = "my-vnet"
address_space       = ["10.0.0.0/16"]
subnet_name         = "my-subnet"
subnet_prefixes     = ["10.0.1.0/24"]
public_ip_name      = "my-pip"
vm_name             = "my-vm"
admin_username      = "azureuser"
ssh_public_key      = "ssh-rsa AAAA..."
