name: Terraform — Azure VM Deploy

on:
  workflow_dispatch:    # manual trigger
  push:
    branches:
      - main            # auto trigger on push to main
    paths:
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - main            # trigger on pull requests
    paths:
     - ".github/workflows/main.yml"

env:
  TF_VERSION: "1.7.5"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}

defaults:
  run:
    working-directory: ./            # change if your .tf files are in a subfolder

# ─── JOB 1: Plan & Apply me
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write           # needed to post plan output as PR comment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true      # post comment even if plan fails
      
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color

      - name: Output VM Public IP
        run: |
          echo "VM Public IP: $(terraform output -raw public_ip_id)"

